pipeline:
  name: xmpp-interop-tests-drone-plugin
  identifier: xmppinteroptestsdroneplugin
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_xmppinteroptestsdroneplugin
        build: <+input>
  stages:
    - stage:
        name: test-plugin
        identifier: testplugin
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: xmppserver
                  identifier: xmppserver
                  spec:
                    connectorRef: Openfire_GitHub_Package_Registry
                    image: ghcr.io/igniterealtime/openfire:main
                    shell: Sh
                    entrypoint:
                      - /sbin/entrypoint.sh
                      - "-demoboot"
                contextType: Pipeline
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push to GHCR
                  identifier: Build_and_push_to_GHCR
                  spec:
                    connectorRef: GitHub_Container_Registry
                    repo: ghcr.io/xmpp-interop-testing/sintse-drone
                    tags:
                      - internal-ci
              - step:
                  type: Plugin
                  name: Run Drone plugin against XMPP server
                  identifier: Run_Drone_plugin_against_XMPP_server
                  spec:
                    connectorRef: GitHub_Container_Registry
                    image: ghcr.io/xmpp-interop-testing/sintse-drone:internal-ci
                    settings:
                      DOMAIN: example.org
                      HOST: xmppserver
                      ADMINACCOUNTUSERNAME: admin
                      ADMINACCOUNTPASSWORD: admin
                      ENABLEDSPECIFICATIONS: XEP-0115,XEP-0199,XEP-0352
                  description: Executes the Drone Plugin against the XMPP server that has been created earlier in this Pipeline.
