pipeline:
  name: xmpp-interop-tests-drone-plugin
  identifier: xmppinteroptestsdroneplugin
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_xmppinteroptestsdroneplugin
        build: <+input>
  stages:
    - stage:
        name: test-plugin
        identifier: testplugin
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Start Openfire
                  identifier: Start_Openfire
                  spec:
                    uses: https://github.com/igniterealtime/Openfire/tree/main/.github/actions/startserver-action
